#!/bin/bash

set -e

# Get Resources

cd ~/Downloads
wget -O hyper.deb https://github.com/vercel/hyper/releases/download/3.0.2/hyper_3.0.2_amd64.deb
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb


# Installers
sudo apt update
sudo apt install software-properties-common apt-transport-https wget

# Install Downloaded packages
sudo apt install -y ./hyper.deb
sudo apt install -y ./google-chrome-stable_current_amd64.deb

# Install Editors
sudo snap install intellij-idea-community --classic
sudo snap install code --classic

# Install communications
sudo snap install slack --classic

# app dev sdk/tools
sudo apt update
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
source ~/.bashrc
nvm --version
nvm install v14.2.0
echo "Node Version: "
node -v
echo "\n\n"

curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk version
sdk install java 11.0.8-amzn
sdk use java 8.0.262-amzn
echo "\n\n"

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt install --no-install-recommends yarn
echo "Yarn Version"
yarn --version
echo "\n\n"
