#!/bin/bash

set -e

# Get Resources

cd ~/Downloads
wget -O hyper.deb https://github.com/vercel/hyper/releases/download/3.0.2/hyper_3.0.2_amd64.deb
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb


# Installers
sudo apt update
sudo apt install software-properties-common apt-transport-https wget build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev

# Install Downloaded packages
sudo apt install -y ./hyper.deb
sudo apt install -y ./google-chrome-stable_current_amd64.deb

# Install Editors
sudo snap install intellij-idea-community --classic
sudo snap install code --classic

# Install communications
sudo snap install slack --classic

# NodeJS
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install nodejs

# app dev sdk/tools
curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk version
sdk install java 11.0.8-amzn
echo "\n\n"

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt install --no-install-recommends yarn
echo "Yarn Version"
yarn --version
echo "\n\n"
